# Generated by Django 4.2.11 on 2024-05-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0003_likedpost_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedpost',
            options={'ordering': ['-created'], 'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
